import type { Language } from "../../i18n";

export const threadCopy = {
  zh: {
    searchPlaceholder: "搜索标题和会话内容",
    clear: "清空",
    conversation: "对话",
    external: "外部",
    subagent: "子代理",
    allKinds: "全部类型",
    active: "活跃",
    archived: "已归档",
    allStatuses: "全部状态",
    selectAll: "全选全部会话",
    export: "导出会话",
    import: "导入会话",
    moveToBin: "移动到回收站",
    archive: "归档",
    sync: "刷新会话",
    syncSuccess: "会话列表已从本地 rollout 刷新",
    restartChatGpt: "重启 ChatGPT",
    restartChatGptConfirmTitle: "确认重启 ChatGPT？",
    restartChatGptConfirmDescription: "这会关闭并重新启动本机 ChatGPT/Codex。",
    restartChatGptSuccess: "ChatGPT/Codex 已重启",
    repair: "修复可见性",
    bin: "回收站",
    noProject: "未归属项目",
    empty: "暂无 Codex 会话",
    noMatch: "没有匹配的会话",
    untitled: "未命名会话",
    sessions: "条会话",
    listTitle: "标题",
    sessionCount: "会话数",
    conversationTime: "对话时间",
    account: "所属账户",
    unknownAccount: "账户未知",
    currentAccount: "当前账户",
    migrate: "迁移到当前账户",
    migrateConfirmTitle: "迁移会话到当前账户？",
    migrateConfirmDescription: "这会保留原会话，并创建一个由当前账户继续使用的新会话。",
    migrateSuccess: "会话已迁移到当前账户",
    inputTokens: "输入",
    outputTokens: "输出",
    totalTokens: "总计",
    openFolder: "打开所在目录",
    openFile: "打开 rollout 文件",
    copyId: "复制会话 ID",
    viewDetails: "查看摘要与时间线",
    detailTitle: "会话详情",
    detailLoading: "正在读取会话详情…",
    detailEmpty: "这条会话没有可显示的消息或工具调用。",
    userSummary: "首条用户请求",
    assistantSummary: "最近助手回复",
    startedAt: "开始",
    updatedAt: "更新",
    lineCount: "行",
    eventCount: "事件",
    toolCallCount: "工具调用",
    source: "来源",
    modelProvider: "模型 Provider",
    cliVersion: "Codex CLI",
    resumeCommand: "继续会话命令",
    copyCommand: "复制命令",
    commandCopied: "继续会话命令已复制",
    resumeNow: "在原目录继续",
    resumeElsewhere: "换目录继续",
    resumeElsewhereHint: "换目录只影响本次启动，不会改写会话记录。",
    rebindDirectory: "永久改目录",
    chooseRebindDirectoryTitle: "选择会话今后使用的项目目录",
    rebindTitle: "永久修改会话目录",
    rebindDescription: "确认后，后续直接继续这条会话时将使用新目录。",
    rebindOld: "当前目录",
    rebindNew: "新目录",
    rebindImpact: "将更新 {files} 个 rollout 文件、{db} 行 state DB 和 {catalog} 行 thread catalog。",
    rebindIndex: "会话标题与 session_index.jsonl 保持原样，并作为确认前置条件校验。",
    rebindRollback: "写入前创建本地恢复点；失败或中断会自动恢复所有已改内容。",
    confirmRebind: "确认永久修改",
    loadMore: "加载更多",
    timelineProgress: "已显示 {shown} / {total} 项",
    timelineReloaded: "会话在读取期间发生变化，时间线已从头重新加载",
    userMessage: "用户",
    assistantMessage: "助手",
    toolCall: "工具",
    toolInput: "输入",
    toolOutput: "输出",
    pending: "等待结果",
    completed: "已完成",
    errored: "失败",
    truncated: "内容已按安全上限截断",
    trashTitle: "Codex 会话回收站",
    trashEmpty: "回收站为空",
    restore: "恢复",
    deleteForever: "永久删除",
    emptyBin: "清空回收站",
    close: "关闭",
    pickOne: "请至少选择一条会话",
    confirmTrash: "所选会话将移到本地回收站，可在之后恢复。",
    trashPreviewSummary: "本次将移动 {count} 条会话，共 {size}。",
    trashRestorePoint: "每条会话都会先写入本地还原清单，再移动原始文件。",
    trashRollback: "任一步骤失败时，文件、索引和可见性状态会自动整体回滚。",
    trashMoreItems: "另有 {count} 条会话未在此处展开。",
    archivePreviewSummary: "本次将归档 {count} 条 active 会话，共 {size}。",
    archiveConflictCheck: "已确认归档目标不存在，原始文件与官方状态仍和预览一致。",
    archiveIndexPreserved: "会话标题和最近会话索引会原样保留，归档后仍可搜索。",
    archiveRollback: "任一步失败或中途退出时，文件与官方可见性会整批恢复到 active 状态。",
    restorePreviewSummary: "本次将恢复 {count} 条会话，共 {size}。",
    restoreConflictCheck: "已确认目标文件、会话索引和当前隐藏状态均无冲突。",
    restoreRollback: "任一步骤失败时，文件、索引和可见性状态会自动整体回到恢复前。",
    confirmDelete: "所选会话将被永久删除，且无法恢复。",
    confirmEmpty: "回收站中的所有会话都将被永久删除，且无法恢复。",
    purgePreviewSummary: "本次将永久清除 {count} 条会话，共 {size}。",
    purgeRestorePoint: "删除前会创建临时本地恢复点；任一步失败会整体回滚。",
    purgePermanent: "验证成功后会销毁恢复 payload，随后无法恢复这些会话。",
    transferPreview: "会话包预览",
    exportHint: "会话包只包含 rollout 文件与本地索引，不包含账号、Token、API Key 或应用设置。",
    importHint: "已存在相同 ID 的会话会自动跳过，不会覆盖本地内容。",
    packageCount: "可处理 {ready} / {total} 条，合计 {size}",
    continueExport: "选择保存位置",
    continueImport: "导入所选会话",
    transfer: "导入/导出",
    duplicate: "已存在",
    ready: "可导入",
    repairTitle: "Codex 会话不可见",
    repairMessage: "以本地 active rollout 为事实来源，校正影响 Codex 侧边栏显示的官方状态。必须先预览，再使用一次性确认。",
    repairMode: "修复方式",
    quick: "快速修复",
    quickDesc: "校正 canonical/legacy state DB 与现有 thread catalog；不改写 rollout。",
    deep: "深度修复",
    deepDesc: "在快速修复基础上补全本地 session index，保留未知和已有条目。",
    sessionScope: "会话范围",
    allSessions: "全部会话",
    allSessionsDesc: "修复当前列表中的全部会话。",
    selectedSessions: "所选会话",
    selectedSessionsDesc: "仅修复已勾选的 {count} 条会话。",
    selectedEmpty: "先在列表中勾选会话。",
    preview: "查看影响范围",
    previewing: "正在查看…",
    startRepair: "确认修复",
    repairing: "正在修复…",
    previewResult: "扫描 {sessions} 条：state 更新 {stateUpdates}、插入 {stateInserts}，catalog 更新 {catalog}，索引新增 {indexAdds}、补全 {indexUpdates}。",
    previewRolloutGuard: "{files} 个 rollout 仅做内容版本校验，源文件保持不变。",
    previewTransactionSafety: "确认令牌绑定本次预览；写入持有共享互斥，失败或中断会自动恢复。",
    loading: "正在读取 Codex 会话…",
  },
  en: {
    searchPlaceholder: "Search titles and conversation content",
    clear: "Clear",
    conversation: "Conversation",
    external: "External",
    subagent: "Subagent",
    allKinds: "All types",
    active: "Active",
    archived: "Archived",
    allStatuses: "All statuses",
    selectAll: "Select all sessions",
    export: "Export sessions",
    import: "Import sessions",
    moveToBin: "Move to Trash",
    archive: "Archive",
    sync: "Refresh sessions",
    syncSuccess: "Session list refreshed from local rollouts",
    restartChatGpt: "Restart ChatGPT",
    restartChatGptConfirmTitle: "Restart ChatGPT?",
    restartChatGptConfirmDescription: "This closes and relaunches local ChatGPT/Codex.",
    restartChatGptSuccess: "ChatGPT/Codex restarted",
    repair: "Repair visibility",
    bin: "Trash",
    noProject: "No project",
    empty: "No Codex sessions yet",
    noMatch: "No matching sessions",
    untitled: "Untitled session",
    sessions: "sessions",
    listTitle: "Title",
    sessionCount: "Sessions",
    conversationTime: "Conversation time",
    account: "Account",
    unknownAccount: "Unknown account",
    currentAccount: "Current account",
    migrate: "Migrate to current account",
    migrateConfirmTitle: "Migrate sessions to the current account?",
    migrateConfirmDescription: "The original sessions stay intact and new sessions are created for the current account.",
    migrateSuccess: "Sessions migrated to the current account",
    inputTokens: "Input",
    outputTokens: "Output",
    totalTokens: "Total",
    openFolder: "Open containing folder",
    openFile: "Open rollout file",
    copyId: "Copy session ID",
    viewDetails: "View summary and timeline",
    detailTitle: "Session details",
    detailLoading: "Loading session details…",
    detailEmpty: "This session has no displayable messages or tool calls.",
    userSummary: "First user request",
    assistantSummary: "Latest assistant response",
    startedAt: "Started",
    updatedAt: "Updated",
    lineCount: "lines",
    eventCount: "events",
    toolCallCount: "tool calls",
    source: "Source",
    modelProvider: "Model provider",
    cliVersion: "Codex CLI",
    resumeCommand: "Resume command",
    copyCommand: "Copy command",
    commandCopied: "Resume command copied",
    resumeNow: "Resume in saved folder",
    resumeElsewhere: "Resume elsewhere",
    resumeElsewhereHint: "The selected folder applies to this launch only; saved session metadata is unchanged.",
    rebindDirectory: "Change saved folder",
    chooseRebindDirectoryTitle: "Choose the session's new saved project folder",
    rebindTitle: "Change the saved session folder",
    rebindDescription: "Future direct resumes of this session will use the new folder.",
    rebindOld: "Current",
    rebindNew: "New",
    rebindImpact: "Updates {files} rollout files, {db} state DB rows, and {catalog} catalog rows.",
    rebindIndex: "The title and session_index.jsonl stay unchanged and are checked before commit.",
    rebindRollback: "A local recovery point is created first; failures or interruptions roll back every change.",
    confirmRebind: "Change saved folder",
    loadMore: "Load more",
    timelineProgress: "Showing {shown} of {total}",
    timelineReloaded: "The session changed while loading; the timeline was reloaded from the start",
    userMessage: "User",
    assistantMessage: "Assistant",
    toolCall: "Tool",
    toolInput: "Input",
    toolOutput: "Output",
    pending: "Pending",
    completed: "Completed",
    errored: "Failed",
    truncated: "Content truncated at the safety limit",
    trashTitle: "Codex Session Trash",
    trashEmpty: "Trash is empty",
    restore: "Restore",
    deleteForever: "Delete permanently",
    emptyBin: "Empty Trash",
    close: "Close",
    pickOne: "Select at least one session",
    confirmTrash: "Selected sessions will move to local Trash and can be restored later.",
    trashPreviewSummary: "This will move {count} sessions totaling {size}.",
    trashRestorePoint: "A local recovery manifest is written before each original file is moved.",
    trashRollback: "If any step fails, files, index entries, and visibility state roll back together.",
    trashMoreItems: "{count} more sessions are not expanded here.",
    archivePreviewSummary: "This will archive {count} active sessions totaling {size}.",
    archiveConflictCheck: "Archive targets are free and source files plus official state still match this preview.",
    archiveIndexPreserved: "Session titles and recent-session index entries are preserved for search.",
    archiveRollback: "If any step fails or the app exits mid-operation, files and official visibility roll back to active as one batch.",
    restorePreviewSummary: "This will restore {count} sessions totaling {size}.",
    restoreConflictCheck: "Destination files, index entries, and current hidden state have no conflicts.",
    restoreRollback: "If any step fails, files, index entries, and visibility state return to their pre-restore state.",
    confirmDelete: "Selected sessions will be permanently deleted and cannot be restored.",
    confirmEmpty: "Every session in Trash will be permanently deleted and cannot be restored.",
    purgePreviewSummary: "This will permanently purge {count} sessions totaling {size}.",
    purgeRestorePoint: "A temporary local restore point is created first; any failure rolls the full batch back.",
    purgePermanent: "After verification, the restore payload is destroyed and these sessions cannot be recovered.",
    transferPreview: "Session package preview",
    exportHint: [
      "The package contains rollout files and the local index only.",
      "Accounts, tokens, API keys, and settings are excluded.",
    ].join(" "),
    importHint: "Sessions with the same ID are skipped and local content is never overwritten.",
    packageCount: "{ready} of {total} ready · {size}",
    continueExport: "Choose save location",
    continueImport: "Import selected sessions",
    transfer: "Import / Export",
    duplicate: "Already exists",
    ready: "Ready",
    repairTitle: "Codex sessions are not visible",
    repairMessage: [
      "Use active local rollouts as the source of truth and correct official state that affects",
      "Codex sidebar visibility. Preview is required before a one-time confirmation.",
    ].join(" "),
    repairMode: "Repair method",
    quick: "Quick repair",
    quickDesc: "Correct canonical/legacy state DBs and existing thread catalogs without rewriting rollouts.",
    deep: "Deep repair",
    deepDesc: "Also fill gaps in the session index while preserving existing and unknown entries.",
    sessionScope: "Session scope",
    allSessions: "All sessions",
    allSessionsDesc: "Repair every session in the current list.",
    selectedSessions: "Selected sessions",
    selectedSessionsDesc: "Repair the {count} selected sessions only.",
    selectedEmpty: "Select sessions from the list first.",
    preview: "View impact",
    previewing: "Checking…",
    startRepair: "Confirm repair",
    repairing: "Repairing…",
    previewResult: "Scans {sessions}: state updates {stateUpdates}, inserts {stateInserts}, catalog updates {catalog}, index adds {indexAdds}, completions {indexUpdates}.",
    previewRolloutGuard: "{files} rollout files are revision guards only and remain unchanged.",
    previewTransactionSafety: "The one-time confirmation is bound to this preview; shared locking and automatic recovery protect every write.",
    loading: "Loading Codex sessions…",
  },
} as const;

export type ThreadCopy = (typeof threadCopy)[Language];
